# Generated by Django 5.1.6 on 2025-02-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_cal_message_deleted_at_message_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
